version: "3.8"

services:
  crypto-track-web:
    container_name: crypto-track-web
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      target: prod
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.crypto-track-web.rule=Host(`barron.agency`)"
      - "traefik.http.routers.crypto-track-web.entrypoints=websecure"
      - "traefik.http.routers.crypto-track-web.tls.certresolver=letsencrypt"
      - "traefik.http.services.crypto-track-web.loadbalancer.server.port=3000"

networks:
  proxy:
    external: false
    name: proxy
