services:
  demo:
    container_name: crypto-track-web
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
      target: prod
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.demo.rule=Host(`barron.agency`)"
      - "traefik.http.routers.demo.entrypoints=websecure"
      - "traefik.http.routers.demo.tls.certresolver=letsencrypt"
      - "traefik.http.services.demo.loadbalancer.server.port=3000"

networks:
  proxy:
    external: false
    name: proxy
