name: Docker Prod

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Docker run
        run: docker-compose up -d --force-recreate --build
